def transpile_to_js(code):
    js = "// Generated by RijLang\n"
    for line in code.splitlines():
        if "print" in line.lower():
            msg = line.split('"')[1]
            js += f'console.log("{msg}");\n'
    return js
